kind: Deployment
apiVersion: apps/v1
metadata:
  name: fedora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedora
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fedora
    spec:
      volumes:
        - name: example
          persistentVolumeClaim:
            claimName: example-pvc
      containers:
        - name: fedora
          image: fedora
          command:
            - sh
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          tty: true
          volumeMounts:
            - mountPath: /tmp/pvc
              name: example
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
